### ISSUE TITLE
Add Windows CI

### ISSUE THREAD

**Issue by f-f** [f-f/dhall-clj#19]
E.g. see [ClojureScript's AppVeyor config](https://github.com/clojure/clojurescript/blob/master/appveyor.yml)

**Comment by jneira** [comment]
I am afraid i don't have experience about setting up AppVeyor
In my win 10 `lein test` fails with this output : https://gist.github.com/jneira/0400a83c69a0e5b835a75ed8b45b1dfb

I hava to investigate but it should be platform independent false negatives

**Comment by f-f** [comment]
@jneira you were right, the failures were due to poorly-platform-independent test code.

#22 fixes the tests and adds Windows CI 🎉
